/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO1.h
**     Project   : SmartMirror
**     Processor : MC9S12XS128CAL
**     Component : Init_GPIO
**     Version   : Component 01.100, Driver 01.08, CPU db: 3.00.020
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2025-03-22, 18:03
**     Abstract  :
**          This file implements the General Purpose Input Output (J)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO1
**          Device                                         : J
**          Port control                                   : Entire I/O port
**
**          Port direction                                 : Input
**          Port output value                              : no initialization
**          Pull resistor                                  : no initialization
**          Open drain                                     : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO1_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __GPIO1
#define __GPIO1

/* MODULE GPIO1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void GPIO1_Init(void);
/*
** ===================================================================
**     Method      :  GPIO1_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END GPIO1. */
#endif /* ifndef __GPIO1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
