/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PWM8.c
**     Project   : SmartMirror
**     Processor : MC9S12XS128CAL
**     Component : Init_PWM
**     Version   : Component 01.158, Driver 01.13, CPU db: 3.00.020
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2025-03-22, 18:03
**     Abstract  :
**          This file implements the PWM (from channel PWM0 to channel PWMx,
**          the actual count of PWM channels depends on the HCS12 derivative)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**          The Pulse Width Modulation (PWM) definition is based on the HC12
**          PWMdefinitions.Each of the six PWM channels has a programmable
**          period and duty cycle as well as a dedicated counter.A flexible
**          clock select scheme allows a total of four different clock sources
**          to be used with the counters. Each of the modulators can create
**          independent continuous waveforms with software-selectable duty
**          rates from 0% to 100%. The PWM outputs can be programmed as
**          left aligned outputs or center aligned outputs.
**     Settings  :
**          Component name                                 : PWM8
**          Device                                         : PWM
**          Settings                                       : 
**            Clock settings                               : 
**              Prescaler B select                         : 1
**              Clock B frequency                          : 8000 kHz
**              Prescaler A select                         : 1
**              Clock A frequency                          : 8000 kHz
**              Scale value of clock SB                    : 0
**              Clock SB frequency                         : 15.62 kHz
**              Scale value of clock SA                    : 0
**              Clock SA frequency                         : 15.62 kHz
**            Concatenate Channels 6 and 7                 : no
**            Concatenate Channels 4 and 5                 : no
**            Concatenate Channels 2 and 3                 : no
**            Concatenate Channels 0 and 1                 : no
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**            Emergency shutdown settings                  : 
**              Emergency shutdown feature                 : Disabled
**              Input active level                         : Low
**              Shutdown output level                      : Low
**          Channels                                       : 0
**          Interrupts                                     : 
**            Emergency interrupt                          : 
**              Emergency interrupt                        : Disabled
**              Interrupt                                  : Vpwmesdn
**              Priority                                   : 1
**              ISR Name                                   : 
**          Initialization                                 : 
**            PWM Restart                                  : no
**            Call Init method                             : yes
**     Contents  :
**         Init - void PWM8_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/* MODULE PWM8. */
#include "PWM8.h"
/*
** ===================================================================
**     Method      :  PWM8_Init (component Init_PWM)
**
**     Description :
**         This method initializes registers of the PWM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PWM8_Init(void)
{
  /* PWME: PWME7=0,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  setReg8(PWME, 0x00U);                /* Disable all PWM channels */ 
  /* PWMPOL: PPOL7=0,PPOL6=0,PPOL5=0,PPOL4=0,PPOL3=0,PPOL2=0,PPOL1=0,PPOL0=0 */
  setReg8(PWMPOL, 0x00U);               
  /* PWMCLK: PCLK7=0,PCLK6=0,PCLK5=0,PCLK4=0,PCLK3=0,PCLK2=0,PCLK1=0,PCLK0=0 */
  setReg8(PWMCLK, 0x00U);               
  /* PWMCAE: CAE7=0,CAE6=0,CAE5=0,CAE4=0,CAE3=0,CAE2=0,CAE1=0,CAE0=0 */
  setReg8(PWMCAE, 0x00U);               
  /* PWMCTL: CON67=0,CON45=0,CON23=0,CON01=0,PSWAI=0,PFRZ=0,??=0,??=0 */
  setReg8(PWMCTL, 0x00U);               
  /* PWMSCLA: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(PWMSCLA, 0x00U);              
  /* PWMSCLB: BIT7=0,BIT6=0,BIT5=0,BIT4=0,BIT3=0,BIT2=0,BIT1=0,BIT0=0 */
  setReg8(PWMSCLB, 0x00U);              
  /* PWMPRCLK: PCKB2=0,PCKB1=0,PCKB0=0,PCKA2=0,PCKA1=0,PCKA0=0 */
  setReg8(PWMPRCLK, 0x00U);             
  /* PWMSDN: PWMIF=1,PWMIE=0,PWMRSTRT=0,PWMLVL=0,??=0,PWM7IN=0,PWM7INL=0,PWM7ENA=0 */
  setReg8(PWMSDN, 0x80U);               
  /* PWME: PWME7=0,PWME6=0,PWME5=0,PWME4=0,PWME3=0,PWME2=0,PWME1=0,PWME0=0 */
  setReg8(PWME, 0x00U);                /* Enable only configured PWM channels */ 
}
/* END PWM8. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
