/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PWM8.h
**     Project   : SmartMirror
**     Processor : MC9S12XS128CAL
**     Component : Init_PWM
**     Version   : Component 01.158, Driver 01.13, CPU db: 3.00.020
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2025-03-22, 18:26
**     Abstract  :
**          This file implements the PWM (from channel PWM0 to channel PWMx,
**          the actual count of PWM channels depends on the HCS12 derivative)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**          The Pulse Width Modulation (PWM) definition is based on the HC12
**          PWMdefinitions.Each of the six PWM channels has a programmable
**          period and duty cycle as well as a dedicated counter.A flexible
**          clock select scheme allows a total of four different clock sources
**          to be used with the counters. Each of the modulators can create
**          independent continuous waveforms with software-selectable duty
**          rates from 0% to 100%. The PWM outputs can be programmed as
**          left aligned outputs or center aligned outputs.
**     Settings  :
**          Component name                                 : PWM8
**          Device                                         : PWM
**          Settings                                       : 
**            Clock settings                               : 
**              Prescaler B select                         : 1
**              Clock B frequency                          : 6000 kHz
**              Prescaler A select                         : 1
**              Clock A frequency                          : 6000 kHz
**              Scale value of clock SB                    : 0
**              Clock SB frequency                         : 11.71 kHz
**              Scale value of clock SA                    : 0
**              Clock SA frequency                         : 11.71 kHz
**            Concatenate Channels 6 and 7                 : no
**            Concatenate Channels 4 and 5                 : no
**            Concatenate Channels 2 and 3                 : no
**            Concatenate Channels 0 and 1                 : no
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**            Emergency shutdown settings                  : 
**              Emergency shutdown feature                 : Disabled
**              Input active level                         : Low
**              Shutdown output level                      : Low
**          Channels                                       : 0
**          Interrupts                                     : 
**            Emergency interrupt                          : 
**              Emergency interrupt                        : Disabled
**              Interrupt                                  : Vpwmesdn
**              Priority                                   : 1
**              ISR Name                                   : 
**          Initialization                                 : 
**            PWM Restart                                  : no
**            Call Init method                             : yes
**     Contents  :
**         Init - void PWM8_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __PWM8
#define __PWM8

/* MODULE PWM8. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"




void PWM8_Init(void);
/*
** ===================================================================
**     Method      :  PWM8_Init (component Init_PWM)
**
**     Description :
**         This method initializes registers of the PWM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/


/* END PWM8. */

#endif /* ifndef __PWM8 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/

