/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SPI1.c
**     Project   : SmartMirror
**     Processor : MC9S12XS128CAL
**     Component : Init_SPI
**     Version   : Component 01.083, Driver 01.09, CPU db: 3.00.020
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2025-03-22, 18:26
**     Abstract  :
**          This file implements the SPI (SPI0)
**          module initialization according to the Peripheral Initialization
**          Component settings, and defines interrupt service routines prototypes.
**          The SPI includes these distinctive features:
**          • Master mode and slave mode
**          • Bi-directional mode
**          • Slave select output
**          • Mode fault error flag with CPU interrupt capability
**          • Double-buffered data register
**          • Serial clock with programmable polarity and phase
**          • Control of SPI operation during wait mode

**     Settings  :
**          Component name                                 : SPI1
**          Device                                         : SPI0
**          Value of Preselection                          : 0
**          Value of Selection                             : 0
**          Frequency                                      : 3 MHz
**          Mode Select                                    : Slave
**          SS pin mode                                    : General Purpose I/O
**          Allocate SS pin                                : Enabled
**          SS pin                                         : PS7_SS0
**          SS pin signal                                  : 
**          Clock Polarity                                 : active-high
**          Clock Phase                                    : Second edge
**          Data shift order                               : MSB first
**          Bidirectional Mode                             : Disabled
**          Stop in Wait Mode                              : no
**          Output enable in Bidirect.                     : no
**          MISO pin                                       : PS4_MISO0
**          MISO pin signal                                : 
**          MOSI pin                                       : PS5_MOSI0
**          MOSI pin signal                                : 
**          SCK pin                                        : PS6_SCK0
**          SCK pin signal                                 : 
**          Interrupt                                      : Vspi0
**          SPI receive interrupt                          : Disabled
**          SPI transmit interrupt                         : Disabled
**          Interrupt Priority                             : 1
**          ISR name                                       : 
**          Call Init in CPU init. code                    : yes
**          Enable SPI system                              : no
**     Contents  :
**         Init - void SPI1_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE SPI1. */

#include "SPI1.h"

/*
** ===================================================================
**     Method      :  SPI1_Init (component Init_SPI)
**
**     Description :
**         This method initializes registers of the SPI module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void SPI1_Init(void)
{
  /* SPI0CR1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=0,SSOE=0,LSBFE=0 */
  setReg8(SPI0CR1, 0x00U);             /* Disable the SPI0 module and clearing flags in SPISR register */ 
  /* SPI0CR2: ??=0,XFRW=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  setReg8(SPI0CR2, 0x00U);              
  /* SPI0BR: ??=0,SPPR2=0,SPPR1=0,SPPR0=0,??=0,SPR2=0,SPR1=0,SPR0=0 */
  setReg8(SPI0BR, 0x00U);               
  /* SPI0CR1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  setReg8(SPI0CR1, 0x04U);              
}

/* END SPI1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
